# MUSUBI Project Configuration
name: RosterHub
description: OneRoster Japan Profile 1.2.2 対応 教育データ連携ハブ
locale: ja
version: "0.1.0"
created: 2025-12-17
updated: 2025-12-17

# Technology Stack
tech_stack:
  approach: monorepo
  languages:
    - TypeScript 5.7
  backend:
    framework: NestJS 11.x
    runtime: Node.js 20.x
    orm: Prisma 6.x
    database: PostgreSQL 15
    cache: Redis 7
    queue: BullMQ
  frontend:
    framework: React 18
    build: Vite 5
    state: Zustand
    query: TanStack Query 5
  testing:
    unit: Jest 30
    e2e: Supertest
  infrastructure:
    containerization: Docker
    orchestration: Docker Compose

# Implementation Status
status:
  phase: complete
  progress: 100%
  sprints_completed:
    - Sprint 0: Project Setup
    - Sprint 1-2: Database Layer
    - Sprint 3-4: Entity Modules
    - Sprint 5-6: Security & Authentication
    - Sprint 7-8: CSV Import/Export
    - Sprint 9-10: Testing & Documentation
    - Sprint 11-12: CI/CD Pipeline

# Test Results
tests:
  unit:
    total: 126
    passed: 126
    status: PASS
  e2e:
    total: 119
    passed: 119
    status: PASS

# CI/CD
cicd:
  ci:
    platform: GitHub Actions
    workflow: .github/workflows/ci.yml
    jobs:
      - lint
      - unit-tests
      - e2e-tests
      - build
      - docker-build
      - security
  cd:
    platform: GitHub Actions
    workflow: .github/workflows/cd.yml
    registry: ghcr.io
    environments:
      - staging
      - production
  dependabot:
    enabled: true
    ecosystems:
      - npm
      - github-actions
      - docker
